name: Build NotchDrop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build NotchDrop
        run: |
          xcodebuild -project NotchDrop.xcodeproj \
                     -scheme NotchDrop \
                     -configuration Release \
                     -derivedDataPath build
      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: NotchDrop-App
          path: build/Build/Products/Release/NotchDrop.app
